server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:l7o6dF8Zq2B8q2QhP7o5vV9jH1l9N3bC0QyWvE9l8sZbU6dQk1jH9rT5pQ2mX7nC}

spring:
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: http://localhost:8081
          predicates:
            - Path=/inventory/**
        - id: payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/payment/**
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/order/**
        - id: customer-service
          uri: http://localhost:8084
          predicates:
            - Path=/customer/**
